# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"func": "MLE_01_serving.ipynb",
         "Class": "MLE_01_serving.ipynb"}

modules = ["de__extract.py",
           "de__transform.py",
           "de__load.py",
           "ds__load.py",
           "ds__preprocess.py",
           "ds__build_features.py",
           "ds__modelling.py",
           "ds__validate.py",
           "ds__postprocess.py",
           "mle__pipeline_utils.py",
           "mle__serving.py"]

doc_url = "https://{user}.github.io/{repo_name}/src/"

git_url = "https://github.com/{user}/src/tree/{branch}/"

def custom_doc_links(name): return None
